server:
  port: 9092
  servlet:
    context-path: /sb-pro
  
spring:
  application:
    name: sb-pro

  h2:
    console:
      path: /h2-pro
      enabled: true

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: sa

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    
custom:
  readtimeout: 5
  connect-timeout: 5